---
    - name: deploying yum packages
      when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
      yum: name=libselinux-python,gcc,gcc-c++,autoconf state=present
    - name: Creating /usr/local/man
      file:
        path: /usr/local/man
        state: directory
    - name: Creating directory for daemontools source code
      file: path=/usr/src state=directory

    - name: Unarchiving Daemontools Source Code
      unarchive:
        src: daemontools-encore-1.10.tar.gz
        dest: /usr/src
#    - name: Copying fedora-28-supervise-stop.sh
#      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '28'
#      copy: src=fedora-28-supervise-stop.sh dest=/usr/src/daemontools-encore-1.10/rts.tests/supervise-stop.sh
#    - name: Copying fedora-28-supervise-stop.sh
#      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '28'
#      copy: src=fedora-28-svc.sh dest=/usr/src/daemontools-encore-1.10/rts.tests/svc.sh

    - name: Deploying Daemontools Package
      shell: creates=/usr/local/bin/svscanboot chdir=/usr/src/daemontools-encore-1.10 make && make install
      retries: 3

    - name: Symlinking tools to /usr/bin
      loop: [envdir,envuidgid,fghack,multilog,pgrphack,readproctitle,setlock,setuidgid,softlimit,supervise,svc,svok,svscan,svscanboot,svstat,svup,tai64n,tai64nlocal]
      file: src=/usr/local/bin/{{item}} dest=/usr/bin/{{item}} owner=root group=root state=link
        
    - name: Creating /service and /.services Directories
      loop: [/service,/.services]
      file: name={{item}} state=directory owner=root group=root mode=0755

    - name: Copying Daemontools systemd service file
      template: src=daemontools.service.j2 dest=/etc/systemd/system/{{serviceName|default('daemontools')}}.service
      when: ansible_service_mgr == 'systemd'
      register: systemdService

    - name: Enabling Daemontools Service
      systemd: name={{serviceName|default('daemontools')}} enabled=yes


    - name: Starting Daemontools Service
      when: AutoStart is defined and AutoStart
      systemd: name={{serviceName|default('daemontools')}} state=started


    - name: CentOS 6 | Sysv Init Handler
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
      block:
            - copy: src=svscan.conf dest=/etc/init/{{serviceName|default('svscan')}}.conf
              register: sv
            - command: initctl reload-configuration
              when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' and sv.changed
            - command: initctl start {{serviceName|default('svscan')}}
              when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' and sv.changed
